server:
  port: 9090
  context-path: /springboot
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.11:3306/chen?characterEncoding=UTF-8
  mvc:
    view:
      suffix: .jsp
      prefix: /
  http:
    encoding:
      force: true
      charset: UTF-8
mybatis:
  type-aliases-package: com.baizhi.entity

